- name: Copying repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: Installing mongodb
  ansible.builtin.dnf:
    name: mongodb-org
    state: present
- name: Replacing IP address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: Restarting mongodb service
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: true