- name: Installing mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Restart the mysql service
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: true

- name: SetUp Mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1