- name: Installing Node js
  ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

- name: Copying cart service file
  ansible.builtin.copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: Creating user
  ansible.builtin.user:
    name: roboshop

- name: Creating app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
    dest: /app
    remote_src: yes

- name: Installing required packages
  community.general.npm:
    path: /app

- name: Restart the service
  ansible.builtin.service:
    name: cart
    state: restarted
    enabled: true
    daemon_reload: true